# Generated by Django 5.0.3 on 2024-05-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField(default='')),
                ('email', models.EmailField(max_length=100)),
                ('message', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sign_up',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
